dev_ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF/fMaEyNAnCt4zD5dtVGn1r2Q8D/vmk0ireIzGjctNJ tomasz.bielewicz@pm.me"

network_mode: static        # dhcp | static
bridge_interface: en0

dns:
  - 1.1.1.1
  - 8.8.8.8

gateway: 192.168.1.1

nodes:
  jumpbox:
    ip: 192.168.1.10
  node0:
    ip: 192.168.1.11
  node1:
    ip: 192.168.1.12
  server:
    ip: 192.168.1.20
